# Generated by Django 4.0.3 on 2022-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_user_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(default='01/01/01'),
        ),
    ]
