# Generated by Django 4.0.3 on 2022-05-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(default=''),
        ),
    ]
